GET http://localhost:3002/plans

### 

PATCH http://localhost:3002/plans/663c6fc1a3375a03266dac07
Content-Type: application/json

{
    "name": "Jackie",
    "email": "jack_jones@gmail.com",
    "planData": {
        "completed" : false
    }
}

###

POST http://localhost:3002/plans
Content-Type: application/json

{
    "email": "jack_jones@gmail.com",   
    "name": "Jackie",
    "planData": {
        "title" : "TESTINGGG",
        "date" : "2024-10-08T15:55",
        "description" : "THIS IS THE END pt 5000",
        "links" : "https://google.com",
        "location" : "Dubai",
        "completed" : "No"
    }
}

###

GET http://localhost:3002/plans/jack_jones@gmail.com

###

DELETE http://localhost:3002/plans/6654b61379f4b0b21235dfff

###

GET http://localhost:3002/plans/id